apiVersion: {{ template "deployment_api_version" . }}
kind: Deployment
metadata:
  labels:
    app: {{ template "app.name" . }}
    chart: {{ template "app.version" . }}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
    name: {{ .Release.Name }}
    cattle.io/creator: norman
    workload.user.cattle.io/workloadselector: {{ template "app.name" . }}-{{ template "app.version" . }}
  name: {{ template "app.name" . }}
spec:
  revisionHistoryLimit: 10
  template:
    metadata:
      labels:
        workload.user.cattle.io/workloadselector: {{ template "app.name" . }}-{{ template "app.version" . }}
    spec:
      containers:
        - args:
            - -scrape_uri={{ .Values.scrapeUri }}
          image: {{ template "system_default_registry" . }}{{ .Values.image.repository }}:{{ .Values.image.tag }}
          imagePullPolicy: IfNotPresent
          name: clickhouse-exporter
          resources: {}
          securityContext:
            allowPrivilegeEscalation: false
            capabilities: {}
            privileged: false
            procMount: Default
            readOnlyRootFilesystem: false
            runAsNonRoot: false
          stdin: true
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          tty: true
      dnsConfig: {}
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
  updateStrategy:
    rollingUpdate:
      maxUnavailable: 1
    type: RollingUpdate