apiVersion: v1
kind: Service
metadata:
  name: clickhouse-exporter
  labels:
    app: {{ template "app.name" . }}
    chart: {{ template "app.version" . }}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
    kubernetes.io/cluster-service: "true"
spec:
  type: ClusterIP
  sessionAffinity: ClientIP
  selector:
    app: {{ template "app.name" . }}
    chart: {{ template "app.version" . }}
    release: {{ .Release.Name }}
  ports:
    - name: 9116
      port: 9116
      targetPort: 9116
